version: '3.7'

services:  
  web_api:
    image: redis_cart_web_api
    container_name: redis_cart_web_api
    depends_on:
      - "redis_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5300:80"
    links:
      - "redis_image"

  redis_image:
    image: redis
    container_name: redis_cart_cache
    ports:
      - "6379:6379"
